import { NextPage } from 'next'
import { useLayoutEffect } from 'react'
import Head from 'next/head'
import { Sort } from 'UwU/components/OptionsShop'
import Products from 'UwU/components/itemListShop/products'
import SidebarShop from 'UwU/components/SidebarShop'
import { ProductType } from 'UwU/types/products.types'
import { CallApiGet } from 'UwU/components/Main/main.service'
import { typedDispatch } from 'UwU/store'
import { setRenderType } from 'UwU/store/shop.slice'

const Shop: NextPage<{
  prods: ProductType[]
  categories: string[]
}> = ({ prods, categories }) => {
  const dispatch = typedDispatch()

  const handleResize = () => {
    if (window.innerWidth <= 1110) {
      dispatch(setRenderType('cards'))
    }
  }

  useLayoutEffect(() => {
    handleResize()
    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [])
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="justify-start flex w-screen xs:w-full p-3 transition-all">
        <span className="flex mr-4 min-w-[250px] w-64 z-10">
          <span className="fixed ">
            <SidebarShop categories={categories} />
          </span>
        </span>
        <section className="flex flex-col justify-center  w-full">
          <span className="pb-2">
            <Sort />
          </span>
          <Products products={prods} />
        </section>
      </main>
    </>
  )
}

export default Shop

export async function getStaticProps() {
  const res = await Promise.all([
    CallApiGet<ProductType[]>('https://fakestoreapi.com/products'),
    CallApiGet<any>('https://fakestoreapi.com/products/categories'),
  ])

  return { props: { prods: res[0], categories: res[1] } }
}
