import { NextPage } from 'next'
import { useEffect } from 'react'
import Head from 'next/head'
import { Sort } from 'UwU/components/OptionsShop'
import Products from 'UwU/components/productListShop/products'
import SidebarShop from 'UwU/components/SidebarShop'
import { ProductType } from 'UwU/types/products.types'
import { CallApiGet } from 'UwU/components/Main/main.service'
import { typedDispatch, typedUseSelector } from 'UwU/store'
import { setRenderType } from 'UwU/store/shop.slice'
import Header from 'UwU/components/Header'

const Shop: NextPage<{
  prods: ProductType[]
  categories: string[]
}> = ({ prods, categories }) => {
  const dispatch = typedDispatch()
  const showSortPopup = typedUseSelector(
    (s) => s.shopSlice.showSortPopup,
  )

  const handleResize = () => {
    if (window.innerWidth <= 1110) {
      dispatch(setRenderType('cards'))
    }
  }
  console.log(showSortPopup)
  useEffect(() => {
    handleResize()
    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [])
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="justify-center items-start sm:justify-start  flex w-screen xs:w-full p-3 transition-all">
        {showSortPopup && (
          <span
            className="fixed w-screen flex h-screen z-50 -ml-3 -mt-3
                       items-center justify-center bg-opacity-95
                     bg-indigo-50"
          >
            <SidebarShop categories={categories} />
          </span>
        )}

        <span className="w-0 mr-4 sm:min-w-[250px]  sm:w-64 z-10">
          <span className="fixed sm:block hidden top-15">
            <SidebarShop categories={categories} />
          </span>
        </span>
        <section className="flex flex-col sm:items-start items-center justify-center w-full">
          <span className="pb-2 flex z-0">
            <Sort />
          </span>
          <Products products={prods} />
        </section>
      </main>
    </>
  )
}

export default Shop

export async function getStaticProps() {
  const res = await Promise.all([
    CallApiGet<ProductType[]>('https://fakestoreapi.com/products'),
    CallApiGet<any>('https://fakestoreapi.com/products/categories'),
  ])

  return { props: { prods: res[0], categories: res[1] } }
}
