import Head from 'next/head'
import { useContext } from 'react'

export default function Home() {
  return (
    <>
      <Head>
        <title>F-commerce website</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
