import Head from 'next/head'
import Header from 'UwU/components/Header'
import MainBody from 'UwU/components/Main'

const Home = () => {
  return (
    <>
      <Head>
        <title>e-commerce website</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainBody />
    </>
  )
}

export default Home
