import { NextPage } from 'next'
import Head from 'next/head'
import { useContext } from 'react'
import { useQuery } from 'react-query'
import MainBody from 'UwU/components/Main'
import { CallApiGet } from 'UwU/components/Main/main.service'
import { ProductType } from 'UwU/types/products.types'

const Home: NextPage<{ prods: ProductType[] }> = ({ prods }) => {
  const { data, isSuccess, isLoading } = useQuery<ProductType[], any>(
    'products',
    () =>
      CallApiGet<ProductType[]>('https://fakestoreapi.com/products'),
    { initialData: prods },
  )

  return (
    <>
      <Head>
        <title>e-commerce website</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainBody products={data!} />
    </>
  )
}

export default Home

export async function getStaticProps() {
  const prods = await CallApiGet<ProductType[]>(
    'https://fakestoreapi.com/products',
  )
  return { props: { prods } }
}
