import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useQuery } from 'react-query'
import { CallApiGet } from 'UwU/components/Main/main.service'
import ShopBody from 'UwU/components/Shop/shop'
import { Categories, ProductType } from 'UwU/types/products.types'

const ShopCategory: NextPage<{
  prods: ProductType[]
  category: Categories
}> = ({ prods, category }) => {
  const { data } = useQuery<ProductType[], any>(
    'products',
    () =>
      CallApiGet<ProductType[]>(
        'https://fakestoreapi.com/products/category' + category,
      ),
    { initialData: prods },
  )

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShopBody products={data!} />
    </>
  )
}

export default ShopCategory

export const getServerSideProps: GetServerSideProps = async ({
  resolvedUrl,
}) => {
  let category = resolvedUrl.slice(15)

  if (Number(category) || !Categories[category as any])
    return {
      notFound: true,
    }
  console.log(category)
  const prods = await CallApiGet<ProductType[]>(
    'https://fakestoreapi.com/products/category/' + category,
  )
  return { props: { prods } }
}
